stages:
  - build
  - test
  - docker

test:
  image: maven:3.8-openjdk-17
  stage: test
  script:
    - mvn verify
  artifacts:
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository

build:
  image: maven:3.8-openjdk-17
  stage: build
  script:
    - mvn package -DskipTests=true
  dependencies:
    - test
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"
